### ISSUE TITLE
Cartes (fait)

### ISSUE THREAD

**Issue by Shishi42** [Touklakos/XenoKart-Eco-Ultimate-Not-Definitive-Edition#8]
- Generation de la carte
- Generation des cases ( hexagone )

**Comment by Shishi42** [comment]
Fait :
- Generation des cases et de la carte aléatoirement avec des types de cases
- pathfinding
A faire peut-être : 
- refonte graphique

**Comment by Shishibre** [comment]
Fait :
- Generation des cases et de la carte aléatoirement avec des types de cases
- pathfinding
A faire peut-être : 
- refonte graphique
